- id: doi:10.1016/j.conengprac.2019.03.009
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0967066118305057-gr1.jpg

- id: doi:10.1109/lra.2019.2921947
  image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjQ7zvfhi-LX_v1IoPJHszvbBCp7hG8YFm_fnFpGt9SNvBw_rEssxFFpjNI59Tckl_SXM&usqp=CAU