name: on-push
run-name: update citations (on push)

on:
  push:
    branches: [ main ]
    paths:
      - "_data/google-scholar.yaml"
      - "_cite/**"
      - ".github/workflows/on-push.yaml"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  call-update:
    uses: cais-psu/CAIS_Lab_Web/.github/workflows/update-citations.yaml@main
    secrets: inherit        # ← 必须有这一句，才能把仓库 secrets 传给被调用工作流
    with:
      open-pr: false        # 直接提交到 main；若想走 PR，改成 true 并确保仓库允许 Actions 开 PR
