name: on-schedule
on:
  schedule:
    - cron: "0 3 1,15 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  call-update:
    uses: cais-psu/CAIS_Lab_Web/.github/workflows/update-citations.yaml@main
    secrets: inherit        # ⭐⭐ 没有这一行，被调用方拿不到 secrets！
    with:
      open-pr: true
