name: on-schedule

on:
  schedule:
    - cron: "0 3 1,15 * *"   # 每月 1/15 日 03:00 UTC ≈ 每两周
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  call-update:
    uses: cais-psu/CAIS_Lab_Web/.github/workflows/update-citations.yaml@main
    secrets: inherit
    with:
      open-pr: false   # ← 这里改为 false（或者直接删掉）
