name: on-schedule
on:
  schedule:
    - cron: "0 3 1,15 * *"   # 每月 1/15 日 03:00 UTC ≈ 两周一次
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  call-update:
    uses: cais-psu/CAIS_Lab_Web/.github/workflows/update-citations.yaml@main
    secrets: inherit                 # ⭐ 关键！把 secrets 传进复用工作流
    with:
      open-pr: true
