# .github/workflows/on-schedule.yaml
name: on-schedule

on:
  schedule:
    - cron: "0 3 1,15 * *"  # 两次/月 ≈ 每两周；UTC 时间
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  scheduled-update:
    runs-on: ubuntu-latest
    concurrency:
      group: on-schedule-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cite deps
        run: pip install -r _cite/requirements.txt

      - name: Run citations (Manubot / LWT)
        env:
          GOOGLE_SCHOLAR_API_KEY: ${{ secrets.GOOGLE_SCHOLAR_API_KEY }}
        run: python _cite/cite.py

      # —— 可选 OA 图片抽取 —— 
      - name: Extract OA images (optional)
        if: ${{ vars.ENABLE_OA_IMAGES == 'true' }}
        run: |
          pip install pymupdf requests unidecode pyyaml
          python _cite/oa_image.py

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(citations): scheduled update"
          file_pattern: |
            _data/citations.yaml
            images/papers/**/*.*
