name: secret-smoke-test
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Echo event context
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "is_fork=${{ github.event.pull_request.head.repo.fork || 'false' }}"

      - name: Show if secret exists (bool only)
        run: |
          if [ -n "${{ secrets.GOOGLE_SCHOLAR_API_KEY }}" ]; then
            echo "Secret GOOGLE_SCHOLAR_API_KEY is present (but masked)."
          else
            echo "Secret GOOGLE_SCHOLAR_API_KEY is EMPTY or UNDEFINED."
            exit 2
          fi
