name: update-citations-direct
run-name: update citations (direct)

on:
  schedule:
    - cron: "0 3 1,15 * *"   # 每月 1/15 日 03:00 UTC ≈ 每两周一次
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  FORCE_COLOR: true
  GOOGLE_SCHOLAR_API_KEY: ${{ secrets.GOOGLE_SCHOLAR_API_KEY }}

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Assert secret visible in context
        run: |
          if [ -n "${{ secrets.GOOGLE_SCHOLAR_API_KEY }}" ]; then
            echo "secrets.GOOGLE_SCHOLAR_API_KEY is present in context."
          else
            echo "::error::secrets.GOOGLE_SCHOLAR_API_KEY is EMPTY in context."
            exit 2
          fi

      - name: Assert runtime env has key
        run: |
          if [ -n "$GOOGLE_SCHOLAR_API_KEY" ]; then
            echo "RUNTIME env has GOOGLE_SCHOLAR_API_KEY."
          else
            echo "::error::RUNTIME env missing GOOGLE_SCHOLAR_API_KEY."
            exit 2
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install cite deps
        run: python -m pip install --upgrade --requirement ./_cite/requirements.txt

      - name: Build updated citations
        env:   # 再显式注入一遍（双保险）
          GOOGLE_SCHOLAR_API_KEY: ${{ secrets.GOOGLE_SCHOLAR_API_KEY }}
        run: python _cite/cite.py
        timeout-minutes: 15

      - name: Check if citations changed
        id: changed
        uses: tj-actions/verify-changed-files@v18
        with:
          files: |
            _data/citations.yaml

      - name: Commit updated citations to branch
        if: steps.changed.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update citations"

      # 可选：开 PR 而不是直接 push
      # - name: Open pull request with updated citations
      #   if: steps.changed.outputs.files_changed == 'true'
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     branch: citation-update
      #     title: Periodic citation update
      #     body: |
      #       Auto update citations.
