# .github/workflows/update-citations.yaml
name: update-citations

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "_data/google-scholar.yaml"
      - "_cite/**"
      - ".github/workflows/update-citations.yaml"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-citations:
    runs-on: ubuntu-latest
    concurrency:
      group: update-citations-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cite deps
        run: pip install -r _cite/requirements.txt

      - name: Run citations (Manubot / LWT)
        env:
          GOOGLE_SCHOLAR_API_KEY: ${{ secrets.GOOGLE_SCHOLAR_API_KEY }}
        run: python _cite/cite.py

      # —— 可选：给开源论文抓取首图，写入 image 字段（见文件 4）——
      - name: Extract OA images (optional)
        if: ${{ vars.ENABLE_OA_IMAGES == 'true' }}
        run: |
          pip install pymupdf requests unidecode pyyaml
          python _cite/oa_image.py

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(citations): update citations and images"
          file_pattern: |
            _data/citations.yaml
            images/papers/**/*.*
