name: update-citations
run-name: update citations

on:
  workflow_call:
    inputs:
      open-pr:
        type: boolean
    outputs:
      changed:
        value: ${{ jobs.update-citations.outputs.changed }}
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

# 顶层 env（双保险其一；如果调用方没传 secrets，这里会是空）
env:
  FORCE_COLOR: true
  GOOGLE_SCHOLAR_API_KEY: ${{ secrets.GOOGLE_SCHOLAR_API_KEY }}

jobs:
  update-citations:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    # 如果你的 secret 放在某个 Environment（比如 production），务必取消下一行注释：
    # environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 早期断言：明确告诉你 secrets 在当前运行是否可见
      - name: Assert GOOGLE_SCHOLAR_API_KEY visibility
        run: |
          echo "event_name=${{ github.event_name }}"
          if [ -n "${GOOGLE_SCHOLAR_API_KEY}" ]; then
            echo "Top-level env has GOOGLE_SCHOLAR_API_KEY (masked)."
          else
            echo "::notice::Top-level env is empty. If this workflow was called via 'uses:', ensure the caller sets 'secrets: inherit'."
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install Python packages
        run: python -m pip install --upgrade --requirement ./_cite/requirements.txt

      # 学术引用构建；再显式注入 env（双保险其二）
      - name: Build updated citations
        env:
          GOOGLE_SCHOLAR_API_KEY: ${{ secrets.GOOGLE_SCHOLAR_API_KEY }}
        run: |
          python - <<'PY'
          import os, sys
          if not os.getenv("GOOGLE_SCHOLAR_API_KEY"):
              sys.stderr.write("FATAL: GOOGLE_SCHOLAR_API_KEY missing before cite.py\n")
              sys.exit(2)
          PY
          python _cite/cite.py
        timeout-minutes: 15

      - name: Check if citations changed
        id: changed
        uses: tj-actions/verify-changed-files@v18
        with:
          files: |
            _data/citations.yaml

      - name: Commit updated citations to branch
        if: |
          steps.changed.outputs.files_changed == 'true' &&
          inputs.open-pr != true
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update citations"

      - name: Open pull request with updated citations
        if: |
          steps.changed.outputs.files_changed == 'true' &&
          inputs.open-pr == true
        uses: peter-evans/create-pull-request@v6
        with:
          branch: citation-update
          title: Periodic citation update
          body: |
            To see a live preview of this PR, close (don't merge) and reopen it.

    outputs:
      changed: ${{ steps.changed.outputs.files_changed || false }}
